# 常规配置
appname: blog-go-gin
httpport: 8088
runmode: dev
autorender: false
copyrequestbody: true
EnableDocs: true
sqlconn:
sessionon: true
#loglevel: Debug   # PanicLevel FatalLevel  ErrorLevel  WarnLevel  InfoLevel  DebugLevel  TraceLevel

#mysql配置
mysql:
  type: mysql
  user: root
  password: q*egyiKm%4dx
  host: 47.119.168.227
  port: 3306
  dbName: blog

#redis配置
redis:
  redisconn: 47.119.168.227:6379
  redispwd:
  db: 1

#ws配置
ws:
  id: 1
  host: 127.0.0.1
  port: 33000
  debug: true

