# 常规配置
appname: blog-go-gin
httpport: 8088
runmode: dev
autorender: false
copyrequestbody: true
EnableDocs: true
sqlconn:
sessionon: true

#mysql配置
mysql:
  type: mysql
  user: root
  password: root
  host: 47.119.168.227
  port: 3306
  dbName: blog
